### ISSUE TITLE
Stuck at downloading libraries

### ISSUE THREAD

**Issue by EGSP** [StefanLobbenmeier/yt-dlp-compose#40]
![image](https://github.com/StefanLobbenmeier/yt-dlp-compose/assets/34096047/cbf3f14d-d1f6-4aec-8931-63e2ba0af030)

Btw, is there any channel to follow development progress or communicate?

**Comment by StefanLobbenmeier** [comment]
It is not resilient at all against failures in the download. 

I am reworking that part at the moment though, also with the aim to use existing installations of yt-dlp and ffmpeg, so I should also be able to make this a bit more resilient. For now to restart those downloads you can restart the application, but yeah there should be automatic retries, error messages and probably a manual retry button.


> Btw, is there any channel to follow development progress or communicate?

this is the one :) to get updates just watch the repo for now and feel free to ask questions here
